# Generated by Django 5.1.5 on 2025-01-28 18:52

import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='Word value')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Added to dictionary'), (2, 'Declined')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Suspicious word',
                'verbose_name_plural': 'Suspicious words',
            },
        ),
        migrations.CreateModel(
            name='ObsceneWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='Word value')),
                ('normalized_value', models.CharField(max_length=1023, verbose_name='Normalized word value')),
                ('similarity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Obscene word',
                'verbose_name_plural': 'Obscene words',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['normalized_value'], name='obscene_word_value', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
